language: node_js
notifications:
  email: false
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
  - secure: soXrQWKCj45RTi0z4pik0rM4czb1gqXPiVXA2krqy02NH5/1B5IVip2nZsoFJ6LbkdN/BnZHoaBkr2oG7HqcPXFLGyXlQfNM24jmZa/A+qKx1zrSw/NMDI3cB0cLmJ63HK9F/ktxoYQLFDLJZ2wRip5XQlBFiwcqH2ZMU3AxJ1TDMepnVMMA/vsUN0A3kB7J/kShcH2WdP0Ag18fmjEiv6CnO35Bt/n/MmIDcSWEFn0fBDeGVGv8nLnir2rvI7vLfxP5GJUcdwVRi8OSUiYmI/DA7YNoo0WVZZ1jU1YiTQSZ0OKHbTg3PT6P4RW25oM9WctD6L5GfeBzIbKrIBAhryNsAG5wKOMrwOiKFzqpU5v0rlx2Cig50FgbR4N6SCl+bHwOqY+SiEgwoaTW3lV0sSUXnQDqv4KRP3Mfa1SOAVyccArowkDkJwtjHPFfEesU/YCjwPbm7+WfSyUtib4ZzKT3spi3OUg46x/QvIxxQ0T1fIsg5xqwLXQfJjMxYvTpPM2RJG0xpr+RazqkwE9/jjHT9JMCc1KDEEr/RGYmgLbqiKoPgp8cBjSklSv1gezY/UABdFi5lnoOpMdFQVFeghcWDgCNHOQIOKnYNfA1FIY+SIXG79Fc9yrNnocgJWXzTkq5c+6uGNXucRamv/for55k8lku4ZjAINM4VWNE8bM=
